name: Build (Linux)

on:
  push:
    paths:
      - 'source/*'
      - '.github/workflows/linux.yml'
      - 'CMakeLists.txt'
jobs:
  build-linux:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Ninja
      run: pip install ninja

    - name: Setup CUDA
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
        sudo dpkg -i cuda-keyring_1.1-1_all.deb
        sudo apt-get update

        sudo apt-get install -y cuda-nvcc-13-0 cuda-cudart-dev-13-0 libcufft-dev-13-0

        echo "PATH=/usr/local/cuda/bin${PATH:+:${PATH}}" >> $GITHUB_ENV
        echo "CUDA_PATH=/usr/local/cuda" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=/usr/local/cuda/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}" >> $GITHUB_ENV

    - name: Download VapourSynth headers
      run: |
        wget -q -O vs.zip https://github.com/vapoursynth/vapoursynth/archive/refs/tags/R57.zip
        unzip -q vs.zip
        mv vapoursynth*/ vapoursynth

    - name: Configure
      run: cmake -S . -B build -G Ninja
        -D VAPOURSYNTH_INCLUDE_DIRECTORY="`pwd`/vapoursynth/include"
        -D CMAKE_BUILD_TYPE=Release
        -D CMAKE_CXX_COMPILER=g++-12
        -D CMAKE_CXX_FLAGS="-Wall"
        -D CMAKE_CUDA_FLAGS="--threads 0 --use_fast_math -Wno-deprecated-gpu-targets"
        -D CMAKE_CUDA_ARCHITECTURES="75;86-real;89-real;120-real"

    - name: Build
      run: cmake --build build --config Release --verbose

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: VapourSynth-ILS-Linux
        path: build/lib*.so
