name: Build (Windows)

on:
  push:
    paths:
      - 'source/*'
      - '.github/workflows/windows.yml'
  workflow_dispatch:
    inputs:
      tag:
        description: 'which tag to upload to'
        default: ''

jobs:
  build-windows:
    runs-on: windows-2025

    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup Ninja
      run: pip install ninja

    - name: Setup CUDA
      run: |
        curl -s -o cuda_installer.exe -L https://developer.download.nvidia.com/compute/cuda/13.0.1/network_installers/cuda_13.0.1_windows_network.exe
        cuda_installer.exe -s nvcc_13.0 cudart_13.0 cufft_13.0 cufft_dev_13.0 crt_13.0 nvptxcompiler_13.0 nvvm_13.0

    - name: Download VapourSynth headers
      run: |
        curl -s -o vs.zip -L https://github.com/vapoursynth/vapoursynth/archive/refs/tags/R57.zip
        unzip -q vs.zip
        mv vapoursynth-*/ vapoursynth/

    - name: Configure
      run: cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Release
        -D VAPOURSYNTH_INCLUDE_DIRECTORY="%cd%\vapoursynth\include"
        -D CMAKE_CUDA_FLAGS="--threads 0 --use_fast_math --resource-usage -Wno-deprecated-gpu-targets"
        -D CMAKE_CUDA_ARCHITECTURES="75;86-real;89-real;120-real"
        -D CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded
      env:
        CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v13.0

    - name: Build
      run: cmake --build build --verbose

    - name: Prepare for upload
      run: |
        mkdir artifact
        copy build\*.dll artifact
        mkdir cufft
        copy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v13.0\bin\x64\cufft64_*.dll" cufft

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: VapourSynth-ILS-Windows-x64
        path: build/*.dll

    - name: Compress artifact for release
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
      run: |
        cd artifact

        mkdir vs-ils-windows-${{ github.event.inputs.tag }}
        xcopy ils.dll vs-ils-windows-${{ github.event.inputs.tag }} /f
        7z a -t7z -mx=9 ../vs-ils-windows-${{ github.event.inputs.tag }}.7z vs-ils-windows-${{ github.event.inputs.tag }}
        
        cd ../cufft

        mkdir vsmlrt-cuda
        xcopy cufft64_*.dll vsmlrt-cuda /f
        7z a -t7z -mx=9 ../cufft-windows-${{ github.event.inputs.tag }}.7z vsmlrt-cuda

    - name: Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
      with:
        tag_name: ${{ github.event.inputs.tag }}
        files: |
          vs-ils-windows-${{ github.event.inputs.tag }}.7z
          cufft-windows-${{ github.event.inputs.tag }}.7z
        fail_on_unmatched_files: true
        generate_release_notes: false
        prerelease: true
